"""DO NOT EDIT - generated by scripts/schema/generate.py"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

class JurisdictionRecord(BaseModel):
    """Canonical data shape of a single jurisdiction record. See docs/specs/jurisdiction-naming.md (T00-08). The jurisdiction_level enum is aligned with rule-object.schema.json so rule_object.jurisdiction_id can reference a jurisdiction_record.jurisdiction_id directly."""
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    jurisdiction_id: str = Field(..., description='Permanent, opaque kebab-case slug. Hierarchical and self-describing. Never reused once issued. Grammar defined in jurisdiction-naming.md §3.', min_length=2, max_length=120, pattern='^[a-z]{2}(-[a-z]{2})?(-(federal|state|county|municipality|etj|utility-district|drainage-district|river-authority|special)-[a-z0-9]+(-[a-z0-9]+)*)?$')
    canonical_name: str = Field(..., description='Full official name. No abbreviations. Title Case. UTF-8. Diacritics preserved as-is. Apostrophes use U+2019 RIGHT SINGLE QUOTATION MARK.', min_length=1, max_length=200)
    jurisdiction_level: Literal['federal', 'state', 'county', 'municipality', 'etj', 'utility_district', 'drainage_district', 'river_authority', 'special'] = Field(..., description='Aligned with rule-object.schema.json jurisdiction_level enum.')
    parent_jurisdiction_id: Optional[Optional[str]] = Field(None, description='ID of the immediate parent per the AGENTS.md jurisdiction hierarchy. Null only for federal jurisdictions. Multi-parent jurisdictions are not allowed — split into separate records.', min_length=2, max_length=120)
    aliases: Optional[List[Dict[str, Any]]] = Field(None, description='Alternate names observed in source documents. Each alias must declare its type so analysts can weigh matches during ingest (T02-06).')
    fips: Optional[Dict[str, Any]] = Field(None, description='U.S. Census Bureau FIPS identifiers. Required for federal, state, county. Optional for sub-county.')
    geometry_ref: Optional[Optional[str]] = Field(None, description="Opaque pointer to a geometry record in the GIS store. Full GIS schema is T05-01's concern. String-only — no inline geometry.", min_length=1, max_length=200)
    active_from: str = Field(..., description='Date this jurisdiction came into legal existence (incorporation, county formation, district creation). For pre-1900 jurisdictions an analyst-attested approximate date is acceptable.', json_schema_extra={'format': 'date'})
    active_to: Optional[Optional[str]] = Field(None, description='Date this jurisdiction ceased to exist (dissolution, merger, split). Null means currently active.', json_schema_extra={'format': 'date'})
    replaced_by: Optional[List[str]] = Field(None, description='Jurisdiction IDs that replace this record after dissolution/merger/split. Set together with active_to. See jurisdiction-naming.md §8.')
    replaced_from: Optional[List[str]] = Field(None, description='Jurisdiction IDs this record was carved or merged from. Set when this record is the result of a split or merger.')
    notes: Optional[str] = Field(None, description='Free-text analyst notes. Not consumed by the rules engine.')
