"""DO NOT EDIT - generated by scripts/schema/generate.py"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

class EvaluatedLeaf(BaseModel):
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    field: str = Field(..., pattern='^(project|geometry|derived)(\\.[a-z][a-z0-9_]*)+$')
    operator: Literal['=', '!=', '>', '>=', '<', '<=', 'contains', 'intersects', 'exists', 'in', 'not_in']
    expected_value: Optional[Any] = Field(None, description='Threshold from the rule. Omitted for operator = exists.')
    actual_value: Any = Field(..., description='Observed value at evaluation time. May be null when the field was absent from inputs.')
    matched: bool
    evaluation_notes: Optional[str] = Field(None, description="Optional engine notes (e.g. 'value coerced from string to number', 'field absent; treated as null').")


class EvaluatedAll(BaseModel):
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    all: List[EvaluatedCondition]
    matched: bool


class EvaluatedAny(BaseModel):
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    any: List[EvaluatedCondition]
    matched: bool


class EvaluatedNot(BaseModel):
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    not_: EvaluatedCondition = Field(..., alias='not')
    matched: bool


EvaluatedCondition = Union[EvaluatedLeaf, EvaluatedAll, EvaluatedAny, EvaluatedNot]


class PermitExplanation(BaseModel):
    """Structured explanation emitted alongside each fired (or short-circuited) permit by the deterministic rules engine. See docs/specs/explainability.md (T00-05). Defers rule object field shapes to T00-01, ruleset versioning to T00-03, and engine implementation to T03-05."""
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    schema_version: Literal['1.0.0'] = Field(..., description='Version of this explanation record schema. Distinct from ruleset_version.')
    record_kind: Literal['fired', 'not_fired'] = Field(..., description='fired = the rule triggered and a permit is in the matrix. not_fired = a negative explanation (T00-05 §5).')
    evaluation_date: str = Field(..., description='Date the engine evaluated this project. Used by T00-03 to select effective ruleset.', json_schema_extra={'format': 'date'})
    ruleset_version: Dict[str, Any]
    rule_refs: List[Dict[str, Any]] = Field(..., description='The rule(s) this record explains. Multiple entries only when a single permit output is the consensus of overlapping rules (e.g. county + state).')
    jurisdiction_chain: List[Dict[str, Any]] = Field(..., description="Ordered jurisdictions from Federal down to the most specific applicable jurisdiction, per AGENTS.md hierarchy. The rule's own jurisdiction MUST appear in this chain.")
    trigger_path: Optional[Dict[str, Any]] = Field(None, description="The conditions in the rule's triggers tree that were evaluated, with field paths, operators, and observed values. Required when record_kind = fired; for not_fired, this shows up to the failing leaf.")
    applicable_thresholds: Optional[List[Dict[str, Any]]] = Field(None, description="Numeric thresholds that governed the decision, lifted from matching leaves of trigger_path. Empty array when the rule's triggers contained no numeric comparisons.")
    citations: Optional[List[Dict[str, Any]]] = Field(None, description='Copied verbatim from provenance.source_citations of every rule in rule_refs. Order preserved; duplicates collapsed by reference.')
    confidence: Dict[str, Any]
    known_unknowns: Optional[List[Dict[str, Any]]] = Field(None, description="Stated uncertainties. Union of the rule's known_unknowns and engine-detected uncertainties at evaluation time (e.g. partial GIS overlap, intake field missing).")
    advisories: List[Dict[str, Any]] = Field(..., description='At least one advisory MUST be present per AGENTS.md Liability Strategy. Union of rule.advisories and any engine-injected disclaimers (e.g. stale freshness, low confidence).')
    evaluation_trace: List[Dict[str, Any]] = Field(..., description='Exactly six entries, one per AGENTS.md evaluation step (T00-01 §8). Order is fixed: jurisdiction, temporal_validity, project_type, trigger_conditions, spatial_overlays, dependencies.')
    negative_explanation: Optional[Dict[str, Any]] = Field(None, description='Required when record_kind = not_fired. The step that short-circuited and a human-readable reason.')
    reproducibility: Dict[str, Any]
