"""DO NOT EDIT - generated by scripts/schema/generate.py"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

class LeafCondition(BaseModel):
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    field: str = Field(..., description='Dotted snake_case path rooted at project, geometry, or derived.', pattern='^(project|geometry|derived)(\\.[a-z][a-z0-9_]*)+$')
    operator: Literal['=', '!=', '>', '>=', '<', '<=', 'contains', 'intersects', 'exists', 'in', 'not_in']
    value: Optional[Any] = Field(None)


class AllCondition(BaseModel):
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    all: List[Condition]


class AnyCondition(BaseModel):
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    any: List[Condition]


class NotCondition(BaseModel):
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    not_: Condition = Field(..., alias='not')


Condition = Union[LeafCondition, AllCondition, AnyCondition, NotCondition]


class RuleObject(BaseModel):
    """Canonical declarative shape of a single regulatory rule. See docs/specs/rule-object.md (T00-01)."""
    model_config = ConfigDict(extra='forbid', populate_by_name=True)
    rule_id: str = Field(..., description='Stable kebab-case ID, never reused.', pattern='^[a-z][a-z0-9]*(-[a-z0-9]+)+$')
    version: str = Field(..., description='Semver MAJOR.MINOR.PATCH for this rule version.', pattern='^\\d+\\.\\d+\\.\\d+$')
    title: str = Field(..., min_length=1, max_length=80)
    permit_name: str = Field(..., min_length=1)
    permit_code: Optional[str] = Field(None)
    jurisdiction_level: Literal['federal', 'state', 'county', 'municipality', 'etj', 'utility_district', 'drainage_district', 'river_authority', 'special']
    jurisdiction_id: str = Field(..., min_length=1)
    source_agency: str = Field(..., min_length=1)
    applicable_project_types: List[str]
    confidence_tier: Literal[1, 2, 3]
    provenance: Dict[str, Any]
    status: Literal['draft', 'published', 'effective', 'archived']
    effective_from: Optional[str] = Field(None, json_schema_extra={'format': 'date'})
    effective_to: Optional[str] = Field(None, json_schema_extra={'format': 'date'})
    supersedes: Optional[List[str]] = Field(None)
    superseded_by: Optional[str] = Field(None, pattern='^[a-z0-9-]+@\\d+\\.\\d+\\.\\d+$')
    triggers: Condition
    outputs: Dict[str, Any]
    sequencing: Optional[Dict[str, Any]] = Field(None)
    explanations: Dict[str, Any]
    known_unknowns: Optional[List[str]] = Field(None)
    advisories: Optional[List[str]] = Field(None)
    tags: Optional[List[str]] = Field(None)
    notes: Optional[str] = Field(None)
