"""user capability flags

Revision ID: 04a85d8df1a1
Revises: 3c4eea27eb8b
Create Date: 2026-05-27 03:38:26.495464
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '04a85d8df1a1'
down_revision: str | None = '3c4eea27eb8b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows so the NOT NULL add is safe on a
    # populated table (e.g. Postgres); the ORM default handles new inserts.
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'capabilities',
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('capabilities')

    # ### end Alembic commands ###
