"""feedback table

Revision ID: 3772cc4e6b3d
Revises: d4607521958a
Create Date: 2026-05-27 04:25:28.416822
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3772cc4e6b3d'
down_revision: str | None = 'd4607521958a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Feedback is tenant-owned but analyst-triaged: consultants (who set the
# app.current_tenant_id GUC) see only their tenant; the analyst queue path sets
# no GUC and must see all tenants' feedback. The RLS policy therefore admits a
# row when its tenant matches the GUC OR the GUC is unset (analyst path). The
# application layer still scopes consultant queries by tenant_id (defense in
# depth). Postgres-only; SQLite (tests/local) relies on the app-layer scope.
_RLS = (
    "ALTER TABLE feedback ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE feedback FORCE ROW LEVEL SECURITY",
    "CREATE POLICY feedback_tenant_or_analyst ON feedback "
    "USING ("
    "current_setting('app.current_tenant_id', true) IS NULL "
    "OR tenant_id = current_setting('app.current_tenant_id', true)"
    ") WITH CHECK ("
    "current_setting('app.current_tenant_id', true) IS NULL "
    "OR tenant_id = current_setting('app.current_tenant_id', true)"
    ")",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('evaluation_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_by', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'confirmed', 'rejected', name='feedback_status', native_enum=False), nullable=False),
    sa.Column('disposition_note', sa.String(), nullable=True),
    sa.Column('dispositioned_by', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispositioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name=op.f('fk_feedback_project_id_project')),
    sa.ForeignKeyConstraint(['submitted_by'], ['app_user.user_id'], name=op.f('fk_feedback_submitted_by_app_user')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_feedback_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('pk_feedback'))
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for stmt in _RLS:
            op.execute(stmt)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP POLICY IF EXISTS feedback_tenant_or_analyst ON feedback")
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_tenant_id'))

    op.drop_table('feedback')
    # ### end Alembic commands ###
