"""tenancy and project tables

Revision ID: 596070292829
Revises: de8d03a08732
Create Date: 2026-05-26 04:44:51.329260

Tenant isolation is two-layer (ADR-0002). The table DDL below is portable
SQLite<->PostgreSQL. The Row-Level Security backstop is PostgreSQL-only and is
attached at the end of ``upgrade`` behind a dialect check; SQLite has no RLS, so
those statements are skipped there and the application-layer scope
(``ipermit_tenancy.session``) is the sole isolation under SQLite test coverage.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '596070292829'
down_revision: str | None = 'de8d03a08732'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tenant-owned tables that get an RLS policy keyed on the per-connection GUC
# ``app.tenant_id``. Kept in sync with ipermit_tenancy.models.TENANT_OWNED_MODELS.
_TENANT_OWNED_TABLES = ("project", "project_evaluation")
_TENANT_GUC = "app.tenant_id"


def _enable_rls() -> None:
    """Attach PostgreSQL Row-Level Security policies (no-op on other dialects).

    Each tenant-owned table gets RLS enabled (also FORCE, so the table owner is
    not exempt) plus a single policy whose USING/WITH CHECK clause compares the
    row's ``tenant_id`` to ``current_setting('app.tenant_id')``. The service sets
    that GUC per connection/transaction; an unset GUC raises rather than leaks
    (``current_setting(name)`` errors when missing). This is the DB backstop that
    holds even if the application layer forgets a tenant filter.
    """
    if op.get_bind().dialect.name != "postgresql":
        return
    for table in _TENANT_OWNED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_tenant_isolation ON {table} "
            f"USING (tenant_id = current_setting('{_TENANT_GUC}')::integer) "
            f"WITH CHECK (tenant_id = current_setting('{_TENANT_GUC}')::integer)"
        )


def _disable_rls() -> None:
    """Drop the RLS policies added by ``_enable_rls`` (no-op off PostgreSQL)."""
    if op.get_bind().dialect.name != "postgresql":
        return
    for table in _TENANT_OWNED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('individual', 'enterprise', name='tenant_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant'))
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_project_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_membership',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('platform_admin', 'regulatory_analyst', 'consultant_user', name='membership_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_membership_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_membership')),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_membership_user')
    )
    with op.batch_alter_table('tenant_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_membership_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('project_evaluation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_version', sa.JSON(), nullable=False),
    sa.Column('inputs_hash', sa.String(length=128), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_evaluation_project_id_project')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_project_evaluation_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_evaluation'))
    )
    with op.batch_alter_table('project_evaluation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_evaluation_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_evaluation_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###

    # PostgreSQL RLS backstop (ADR-0002); skipped on SQLite.
    _enable_rls()


def downgrade() -> None:
    # PostgreSQL RLS backstop (ADR-0002); skipped on SQLite.
    _disable_rls()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_evaluation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_evaluation_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_project_evaluation_project_id'))

    op.drop_table('project_evaluation')
    with op.batch_alter_table('tenant_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_membership_tenant_id'))

    op.drop_table('tenant_membership')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tenant_id'))

    op.drop_table('project')
    op.drop_table('tenant')
    # ### end Alembic commands ###
