"""billing subscription and webhook event

Revision ID: 6951563f5244
Revises: 3772cc4e6b3d
Create Date: 2026-05-27 04:32:39.850973
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6951563f5244'
down_revision: str | None = '3772cc4e6b3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Subscription is tenant-owned but written by the system webhook path (no tenant
# GUC); like feedback its RLS admits tenant-matched rows OR the unset-GUC system
# path. webhook_event is platform-global (no RLS). Postgres-only; SQLite no-ops.
_RLS = (
    "ALTER TABLE subscription ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE subscription FORCE ROW LEVEL SECURITY",
    "CREATE POLICY subscription_tenant_or_system ON subscription "
    "USING ("
    "current_setting('app.current_tenant_id', true) IS NULL "
    "OR tenant_id = current_setting('app.current_tenant_id', true)"
    ") WITH CHECK ("
    "current_setting('app.current_tenant_id', true) IS NULL "
    "OR tenant_id = current_setting('app.current_tenant_id', true)"
    ")",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event',
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_webhook_event'))
    )
    op.create_table('subscription',
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'trialing', 'past_due', 'canceled', 'incomplete', name='subscription_status', native_enum=False), nullable=False),
    sa.Column('external_customer_id', sa.String(length=120), nullable=True),
    sa.Column('external_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_subscription_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('subscription_id', name=op.f('pk_subscription')),
    sa.UniqueConstraint('external_subscription_id', name=op.f('uq_subscription_external_subscription_id')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_subscription_tenant_id'))
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for stmt in _RLS:
            op.execute(stmt)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP POLICY IF EXISTS subscription_tenant_or_system ON subscription")
    op.drop_table('subscription')
    op.drop_table('webhook_event')
    # ### end Alembic commands ###
