"""billing tables

Revision ID: 699a410cd559
Revises: 3772cc4e6b3d
Create Date: 2026-05-27 05:28:24.357144
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '699a410cd559'
down_revision: str | None = '3772cc4e6b3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# tenant_billing is tenant-owned, so it gets Postgres Row-Level Security keyed on
# the app.current_tenant_id GUC (ADR-0002), exactly like project/evaluation.
# processed_stripe_event is platform-global (the Stripe event id is account-wide
# and the webhook arrives unauthenticated) — no tenant_id, so no RLS. SQLite
# (tests/local) has no RLS; isolation there relies on the app-layer tenant scope.
_RLS_TABLE = "tenant_billing"


def _enable_rls() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute(f"ALTER TABLE {_RLS_TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {_RLS_TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY {_RLS_TABLE}_tenant_isolation ON {_RLS_TABLE} "
        "USING (tenant_id = current_setting('app.current_tenant_id', true)) "
        "WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true))"
    )


def _disable_rls() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute(
        f"DROP POLICY IF EXISTS {_RLS_TABLE}_tenant_isolation ON {_RLS_TABLE}"
    )
    op.execute(f"ALTER TABLE {_RLS_TABLE} DISABLE ROW LEVEL SECURITY")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_stripe_event',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_processed_stripe_event'))
    )
    op.create_table('tenant_billing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('free', 'starter', 'pro', name='billing_plan', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('none', 'active', 'past_due', 'canceled', 'incomplete', name='billing_status', native_enum=False), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_tenant_billing_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_billing')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_billing_tenant_id'))
    )
    # ### end Alembic commands ###
    _enable_rls()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _disable_rls()
    op.drop_table('tenant_billing')
    op.drop_table('processed_stripe_event')
    # ### end Alembic commands ###
