"""initial jurisdiction tables

Revision ID: 89628ebc067c
Revises:
Create Date: 2026-05-25 03:30:20.054240
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '89628ebc067c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdiction',
    sa.Column('jurisdiction_id', sa.String(length=120), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('jurisdiction_level', sa.Enum('federal', 'state', 'county', 'municipality', 'etj', 'utility_district', 'drainage_district', 'river_authority', 'special', name='jurisdiction_level', native_enum=False), nullable=False),
    sa.Column('parent_jurisdiction_id', sa.String(length=120), nullable=True),
    sa.Column('fips_state', sa.String(length=2), nullable=True),
    sa.Column('fips_county', sa.String(length=5), nullable=True),
    sa.Column('fips_place', sa.String(length=7), nullable=True),
    sa.Column('geometry_ref', sa.String(length=200), nullable=True),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('replaced_by', sa.JSON(), nullable=False),
    sa.Column('replaced_from', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_jurisdiction_id'], ['jurisdiction.jurisdiction_id'], name=op.f('fk_jurisdiction_parent_jurisdiction_id_jurisdiction')),
    sa.PrimaryKeyConstraint('jurisdiction_id', name=op.f('pk_jurisdiction'))
    )
    op.create_table('jurisdiction_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('alias_type', sa.Enum('abbreviation', 'historical', 'colloquial', 'misspelling', name='alias_type', native_enum=False), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdiction.jurisdiction_id'], name=op.f('fk_jurisdiction_alias_jurisdiction_id_jurisdiction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jurisdiction_alias'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jurisdiction_alias')
    op.drop_table('jurisdiction')
    # ### end Alembic commands ###
