"""regulatory rule + citation tables

Revision ID: 8c9f47be8813
Revises: 89628ebc067c
Create Date: 2026-05-25 03:43:40.907282
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8c9f47be8813'
down_revision: str | None = '89628ebc067c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_rule',
    sa.Column('rule_id', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('permit_name', sa.String(length=200), nullable=False),
    sa.Column('permit_code', sa.String(length=80), nullable=True),
    sa.Column('jurisdiction_level', sa.Enum('federal', 'state', 'county', 'municipality', 'etj', 'utility_district', 'drainage_district', 'river_authority', 'special', name='rule_jurisdiction_level', native_enum=False), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=200), nullable=False),
    sa.Column('source_agency', sa.String(length=300), nullable=False),
    sa.Column('confidence_tier', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'effective', 'archived', name='rule_status', native_enum=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=True),
    sa.Column('applicable_project_types', sa.JSON(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('rule_id', 'version', name=op.f('pk_regulatory_rule'))
    )
    op.create_table('regulatory_citation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('citation_type', sa.Enum('statute', 'regulation', 'ordinance', 'agency_guidance', 'form', 'website', name='citation_type', native_enum=False), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id', 'version'], ['regulatory_rule.rule_id', 'regulatory_rule.version'], name='fk_regulatory_citation_rule'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulatory_citation'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regulatory_citation')
    op.drop_table('regulatory_rule')
    # ### end Alembic commands ###
