"""rule publication workflow

Revision ID: b4786b301ca7
Revises: a1b2c3d4e5f6
Create Date: 2026-05-28 04:58:12.080465
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b4786b301ca7'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_publication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.String(length=120), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('target_status', sa.Enum('effective', 'archived', name='publication_target', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', 'rolled_back', name='publication_status', native_enum=False), nullable=False),
    sa.Column('proposed_by', sa.String(length=320), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('decided_by', sa.String(length=320), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_publication'))
    )
    with op.batch_alter_table('rule_publication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_publication_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_publication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_publication_rule_id'))

    op.drop_table('rule_publication')
    # ### end Alembic commands ###
