"""source check table

Revision ID: de8d03a08732
Revises: 8c9f47be8813
Create Date: 2026-05-25 07:38:30.503985
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'de8d03a08732'
down_revision: str | None = '8c9f47be8813'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('checked_at', sa.Date(), nullable=False),
    sa.Column('url_reachable', sa.Boolean(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('form_changed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id', 'version'], ['regulatory_rule.rule_id', 'regulatory_rule.version'], name='fk_source_check_rule'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_check'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_check')
    # ### end Alembic commands ###
