"""Shared helpers for the schema codegen and validation scripts (T01-11).

The canonical JSON Schemas under docs/specs/schemas/ are the single source of
truth. These helpers locate the repo root, load the schemas, and map schema
file names to stable module / type names. No hand-editing of generated output.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

# Map: schema file stem -> (python module name, TypeScript root type name).
# Kept explicit so generated identifiers stay stable and reviewable.
SCHEMA_NAMES: dict[str, tuple[str, str]] = {
    "rule-object": ("rule_object", "RuleObject"),
    "jurisdiction-record": ("jurisdiction_record", "JurisdictionRecord"),
    "permit-explanation": ("permit_explanation", "PermitExplanation"),
    "benchmark-project": ("benchmark_project", "BenchmarkProject"),
}

GENERATED_HEADER = "DO NOT EDIT - generated by scripts/schema/generate.py"


def repo_root() -> Path:
    """Return the worktree root by walking up to the directory holding AGENTS.md."""
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "AGENTS.md").exists():
            return parent
    raise RuntimeError("Could not locate repo root (no AGENTS.md found).")


def schemas_dir() -> Path:
    """Directory containing the canonical *.schema.json files."""
    return repo_root() / "docs" / "specs" / "schemas"


def load_schema(stem: str) -> dict:
    """Load one schema by its file stem (e.g. 'rule-object')."""
    path = schemas_dir() / f"{stem}.schema.json"
    return json.loads(path.read_text(encoding="utf-8"))


def to_pascal_case(name: str) -> str:
    """Convert a snake_case or kebab-case token to PascalCase."""
    parts = re.split(r"[-_\s]+", name.strip())
    return "".join(part[:1].upper() + part[1:] for part in parts if part)
