// DO NOT EDIT - generated by scripts/schema/generate.py

* This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical data shape of a single jurisdiction record. See docs/specs/jurisdiction-naming.md (T00-08). The jurisdiction_level enum is aligned with rule-object.schema.json so rule_object.jurisdiction_id can reference a jurisdiction_record.jurisdiction_id directly.
 */
export type JurisdictionRecord = {
  [k: string]: unknown;
} & {
  /**
   * Permanent, opaque kebab-case slug. Hierarchical and self-describing. Never reused once issued. Grammar defined in jurisdiction-naming.md §3.
   */
  jurisdiction_id: string;
  /**
   * Full official name. No abbreviations. Title Case. UTF-8. Diacritics preserved as-is. Apostrophes use U+2019 RIGHT SINGLE QUOTATION MARK.
   */
  canonical_name: string;
  /**
   * Aligned with rule-object.schema.json jurisdiction_level enum.
   */
  jurisdiction_level:
    | "federal"
    | "state"
    | "county"
    | "municipality"
    | "etj"
    | "utility_district"
    | "drainage_district"
    | "river_authority"
    | "special";
  /**
   * ID of the immediate parent per the AGENTS.md jurisdiction hierarchy. Null only for federal jurisdictions. Multi-parent jurisdictions are not allowed — split into separate records.
   */
  parent_jurisdiction_id?: string | null;
  /**
   * Alternate names observed in source documents. Each alias must declare its type so analysts can weigh matches during ingest (T02-06).
   */
  aliases?: {
    /**
     * The alternate string itself, as it appears in the source.
     */
    value: string;
    /**
     * Why this alias exists. Historical aliases SHOULD set date_from/date_to. Misspellings record observed errors so ingest can normalize them.
     */
    alias_type: "abbreviation" | "historical" | "colloquial" | "misspelling";
    /**
     * Where the alias was observed (URL, statute reference, intake form, etc.).
     */
    source?: string;
    /**
     * First date this alias was in use. Required pattern for historical aliases.
     */
    date_from?: string;
    /**
     * Last date this alias was in use. Null/absent means still current.
     */
    date_to?: string;
    /**
     * Free-text analyst note (e.g. context of a misspelling).
     */
    notes?: string;
  }[];
  /**
   * U.S. Census Bureau FIPS identifiers. Required for federal, state, county. Optional for sub-county.
   */
  fips?: {
    /**
     * Two-digit FIPS state code. Texas is '48'.
     */
    fips_state?: string;
    /**
     * Five-digit FIPS county code (state + county). Travis County, TX is '48453'.
     */
    fips_county?: string;
    /**
     * Seven-digit FIPS place code (state + place). Optional, used for municipalities.
     */
    fips_place?: string;
  };
  /**
   * Opaque pointer to a geometry record in the GIS store. Full GIS schema is T05-01's concern. String-only — no inline geometry.
   */
  geometry_ref?: string | null;
  /**
   * Date this jurisdiction came into legal existence (incorporation, county formation, district creation). For pre-1900 jurisdictions an analyst-attested approximate date is acceptable.
   */
  active_from: string;
  /**
   * Date this jurisdiction ceased to exist (dissolution, merger, split). Null means currently active.
   */
  active_to?: string | null;
  /**
   * Jurisdiction IDs that replace this record after dissolution/merger/split. Set together with active_to. See jurisdiction-naming.md §8.
   */
  replaced_by?: string[];
  /**
   * Jurisdiction IDs this record was carved or merged from. Set when this record is the result of a split or merger.
   */
  replaced_from?: string[];
  /**
   * Free-text analyst notes. Not consumed by the rules engine.
   */
  notes?: string;
};
