// DO NOT EDIT - generated by scripts/schema/generate.py

* This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Structured explanation emitted alongside each fired (or short-circuited) permit by the deterministic rules engine. See docs/specs/explainability.md (T00-05). Defers rule object field shapes to T00-01, ruleset versioning to T00-03, and engine implementation to T03-05.
 */
export type PermitExplanation = {
  [k: string]: unknown;
} & {
  /**
   * Version of this explanation record schema. Distinct from ruleset_version.
   */
  schema_version: "1.0.0";
  /**
   * fired = the rule triggered and a permit is in the matrix. not_fired = a negative explanation (T00-05 §5).
   */
  record_kind: "fired" | "not_fired";
  /**
   * Date the engine evaluated this project. Used by T00-03 to select effective ruleset.
   */
  evaluation_date: string;
  ruleset_version: {
    /**
     * Hash of the effective ruleset snapshot used. Algorithm and snapshotting owned by T00-03.
     */
    content_hash: string;
    /**
     * Git commit SHA of the rules repository if the snapshot maps to one. Optional.
     */
    commit_sha?: string;
    /**
     * Human-readable label for the snapshot (e.g. 2026-05-24-effective).
     */
    snapshot_label?: string;
  };
  /**
   * The rule(s) this record explains. Multiple entries only when a single permit output is the consensus of overlapping rules (e.g. county + state).
   *
   * @minItems 1
   */
  rule_refs: [
    {
      rule_id: string;
      rule_version: string;
      /**
       * Status of the rule object at evaluation_date. archived is only valid for grandfathered replays (T00-03).
       */
      rule_status_at_evaluation?: "effective" | "archived";
    },
    ...{
      rule_id: string;
      rule_version: string;
      /**
       * Status of the rule object at evaluation_date. archived is only valid for grandfathered replays (T00-03).
       */
      rule_status_at_evaluation?: "effective" | "archived";
    }[]
  ];
  /**
   * Ordered jurisdictions from Federal down to the most specific applicable jurisdiction, per AGENTS.md hierarchy. The rule's own jurisdiction MUST appear in this chain.
   *
   * @minItems 1
   */
  jurisdiction_chain: [
    {
      jurisdiction_id: string;
      jurisdiction_level:
        | "federal"
        | "state"
        | "county"
        | "municipality"
        | "etj"
        | "utility_district"
        | "drainage_district"
        | "river_authority"
        | "special";
      canonical_name?: string;
      /**
       * How this jurisdiction entered the evaluation. See T05-04 / T06-02.
       */
      detection_source?: "user_input" | "gis_auto_detect" | "user_confirmed" | "user_override";
    },
    ...{
      jurisdiction_id: string;
      jurisdiction_level:
        | "federal"
        | "state"
        | "county"
        | "municipality"
        | "etj"
        | "utility_district"
        | "drainage_district"
        | "river_authority"
        | "special";
      canonical_name?: string;
      /**
       * How this jurisdiction entered the evaluation. See T05-04 / T06-02.
       */
      detection_source?: "user_input" | "gis_auto_detect" | "user_confirmed" | "user_override";
    }[]
  ];
  /**
   * The conditions in the rule's triggers tree that were evaluated, with field paths, operators, and observed values. Required when record_kind = fired; for not_fired, this shows up to the failing leaf.
   */
  trigger_path?: {
    root: EvaluatedCondition;
    /**
     * Plain-language collapsed restatement of which branches matched. Derived; included for human review.
     */
    matched_summary?: string;
  };
  /**
   * Numeric thresholds that governed the decision, lifted from matching leaves of trigger_path. Empty array when the rule's triggers contained no numeric comparisons.
   */
  applicable_thresholds?: {
    field: string;
    operator: ">" | ">=" | "<" | "<=" | "=" | "!=";
    /**
     * Threshold from the rule. Number or ISO date string.
     */
    threshold_value: {
      [k: string]: unknown;
    };
    /**
     * Observed value from project inputs at evaluation time.
     */
    actual_value: {
      [k: string]: unknown;
    };
    /**
     * Units string for human display (e.g. acres, days, count). Optional; the field registry (T02-02) owns canonical units.
     */
    units?: string;
  }[];
  /**
   * Copied verbatim from provenance.source_citations of every rule in rule_refs. Order preserved; duplicates collapsed by reference.
   *
   * @minItems 1
   */
  citations?: [
    {
      citation_type: "statute" | "regulation" | "ordinance" | "agency_guidance" | "form" | "website";
      reference: string;
      url?: string;
      retrieved_at?: string;
    },
    ...{
      citation_type: "statute" | "regulation" | "ordinance" | "agency_guidance" | "form" | "website";
      reference: string;
      url?: string;
      retrieved_at?: string;
    }[]
  ];
  confidence: {
    /**
     * Confidence tier copied from the rule. When multiple rules contribute, this is the LOWEST (most cautious) tier across rule_refs.
     */
    tier: 1 | 2 | 3;
    /**
     * Plain-language statement of why this tier applies. Combines AGENTS.md tier definitions with rule-specific context.
     */
    tier_rationale: string;
    freshness: {
      last_verified: string;
      days_since_verified: number;
      /**
       * True when days_since_verified exceeds the freshness threshold owned by T02-07. Surfaced independently of confidence per AGENTS.md Data Governance.
       */
      stale: boolean;
      /**
       * Required when stale = true. Human-readable reason (e.g. 'last verified 540 days ago; threshold is 365').
       */
      stale_reason?: string;
    };
  };
  /**
   * Stated uncertainties. Union of the rule's known_unknowns and engine-detected uncertainties at evaluation time (e.g. partial GIS overlap, intake field missing).
   */
  known_unknowns?: {
    text: string;
    /**
     * rule = copied from rule.known_unknowns. engine = detected at evaluation time.
     */
    origin: "rule" | "engine";
    /**
     * Required when origin = engine. Identifier of the engine signal (e.g. partial_gis_overlap, missing_intake_field, citation_url_unreachable).
     */
    engine_signal?: string;
  }[];
  /**
   * At least one advisory MUST be present per AGENTS.md Liability Strategy. Union of rule.advisories and any engine-injected disclaimers (e.g. stale freshness, low confidence).
   *
   * @minItems 1
   */
  advisories: [
    {
      text: string;
      /**
       * platform = the standing advisory required for every permit record (e.g. 'Advisory only; not a legal determination').
       */
      origin: "rule" | "engine" | "platform";
      category:
        | "advisory_disclaimer"
        | "professional_review_required"
        | "agency_coordination"
        | "freshness_warning"
        | "confidence_warning"
        | "jurisdictional_overlap"
        | "data_gap";
    },
    ...{
      text: string;
      /**
       * platform = the standing advisory required for every permit record (e.g. 'Advisory only; not a legal determination').
       */
      origin: "rule" | "engine" | "platform";
      category:
        | "advisory_disclaimer"
        | "professional_review_required"
        | "agency_coordination"
        | "freshness_warning"
        | "confidence_warning"
        | "jurisdictional_overlap"
        | "data_gap";
    }[]
  ];
  /**
   * Exactly six entries, one per AGENTS.md evaluation step (T00-01 §8). Order is fixed: jurisdiction, temporal_validity, project_type, trigger_conditions, spatial_overlays, dependencies.
   *
   * @minItems 6
   * @maxItems 6
   */
  evaluation_trace: [
    {
      step:
        | "jurisdiction"
        | "temporal_validity"
        | "project_type"
        | "trigger_conditions"
        | "spatial_overlays"
        | "dependencies";
      /**
       * skipped = an earlier step short-circuited, so this step was not evaluated.
       */
      outcome: "passed" | "failed" | "skipped";
      /**
       * One-line explanation of the outcome (e.g. 'rule jurisdiction us-federal in chain', 'project_type substation not in applicable_project_types').
       */
      detail?: string;
    },
    {
      step:
        | "jurisdiction"
        | "temporal_validity"
        | "project_type"
        | "trigger_conditions"
        | "spatial_overlays"
        | "dependencies";
      /**
       * skipped = an earlier step short-circuited, so this step was not evaluated.
       */
      outcome: "passed" | "failed" | "skipped";
      /**
       * One-line explanation of the outcome (e.g. 'rule jurisdiction us-federal in chain', 'project_type substation not in applicable_project_types').
       */
      detail?: string;
    },
    {
      step:
        | "jurisdiction"
        | "temporal_validity"
        | "project_type"
        | "trigger_conditions"
        | "spatial_overlays"
        | "dependencies";
      /**
       * skipped = an earlier step short-circuited, so this step was not evaluated.
       */
      outcome: "passed" | "failed" | "skipped";
      /**
       * One-line explanation of the outcome (e.g. 'rule jurisdiction us-federal in chain', 'project_type substation not in applicable_project_types').
       */
      detail?: string;
    },
    {
      step:
        | "jurisdiction"
        | "temporal_validity"
        | "project_type"
        | "trigger_conditions"
        | "spatial_overlays"
        | "dependencies";
      /**
       * skipped = an earlier step short-circuited, so this step was not evaluated.
       */
      outcome: "passed" | "failed" | "skipped";
      /**
       * One-line explanation of the outcome (e.g. 'rule jurisdiction us-federal in chain', 'project_type substation not in applicable_project_types').
       */
      detail?: string;
    },
    {
      step:
        | "jurisdiction"
        | "temporal_validity"
        | "project_type"
        | "trigger_conditions"
        | "spatial_overlays"
        | "dependencies";
      /**
       * skipped = an earlier step short-circuited, so this step was not evaluated.
       */
      outcome: "passed" | "failed" | "skipped";
      /**
       * One-line explanation of the outcome (e.g. 'rule jurisdiction us-federal in chain', 'project_type substation not in applicable_project_types').
       */
      detail?: string;
    },
    {
      step:
        | "jurisdiction"
        | "temporal_validity"
        | "project_type"
        | "trigger_conditions"
        | "spatial_overlays"
        | "dependencies";
      /**
       * skipped = an earlier step short-circuited, so this step was not evaluated.
       */
      outcome: "passed" | "failed" | "skipped";
      /**
       * One-line explanation of the outcome (e.g. 'rule jurisdiction us-federal in chain', 'project_type substation not in applicable_project_types').
       */
      detail?: string;
    }
  ];
  /**
   * Required when record_kind = not_fired. The step that short-circuited and a human-readable reason.
   */
  negative_explanation?: {
    short_circuited_at:
      | "jurisdiction"
      | "temporal_validity"
      | "project_type"
      | "trigger_conditions"
      | "spatial_overlays"
      | "dependencies";
    reason: string;
  };
  reproducibility: {
    /**
     * Hash of the canonical project inputs (intake + confirmed GIS) used. Combined with ruleset_version.content_hash and evaluation_date, this triplet keys the reproducibility contract (§6).
     */
    inputs_hash: string;
    /**
     * Asserts the record was produced by the deterministic engine path; no AI-derived fields are present in this record.
     */
    deterministic: true;
    /**
     * Optional note from the engine about reproducibility caveats (e.g. 'GIS dataset version 2026.04 must be available for replay').
     */
    regeneration_note?: string;
  };
};
export type EvaluatedCondition = EvaluatedLeaf | EvaluatedAll | EvaluatedAny | EvaluatedNot;

export interface EvaluatedLeaf {
  field: string;
  operator: "=" | "!=" | ">" | ">=" | "<" | "<=" | "contains" | "intersects" | "exists" | "in" | "not_in";
  /**
   * Threshold from the rule. Omitted for operator = exists.
   */
  expected_value?: {
    [k: string]: unknown;
  };
  /**
   * Observed value at evaluation time. May be null when the field was absent from inputs.
   */
  actual_value: {
    [k: string]: unknown;
  };
  matched: boolean;
  /**
   * Optional engine notes (e.g. 'value coerced from string to number', 'field absent; treated as null').
   */
  evaluation_notes?: string;
}
export interface EvaluatedAll {
  /**
   * @minItems 1
   */
  all: [EvaluatedCondition, ...EvaluatedCondition[]];
  matched: boolean;
}
export interface EvaluatedAny {
  /**
   * @minItems 1
   */
  any: [EvaluatedCondition, ...EvaluatedCondition[]];
  matched: boolean;
}
export interface EvaluatedNot {
  not: EvaluatedCondition;
  matched: boolean;
}
