// DO NOT EDIT - generated by scripts/schema/generate.py

* This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical declarative shape of a single regulatory rule. See docs/specs/rule-object.md (T00-01).
 */
export type RuleObject = {
  [k: string]: unknown;
} & {
  /**
   * Stable kebab-case ID, never reused.
   */
  rule_id: string;
  /**
   * Semver MAJOR.MINOR.PATCH for this rule version.
   */
  version: string;
  title: string;
  permit_name: string;
  permit_code?: string;
  jurisdiction_level:
    | "federal"
    | "state"
    | "county"
    | "municipality"
    | "etj"
    | "utility_district"
    | "drainage_district"
    | "river_authority"
    | "special";
  jurisdiction_id: string;
  source_agency: string;
  /**
   * @minItems 1
   */
  applicable_project_types: [string, ...string[]];
  confidence_tier: 1 | 2 | 3;
  provenance: {
    /**
     * @minItems 1
     */
    source_citations: [
      {
        citation_type: "statute" | "regulation" | "ordinance" | "agency_guidance" | "form" | "website";
        reference: string;
        url?: string;
        retrieved_at?: string;
      },
      ...{
        citation_type: "statute" | "regulation" | "ordinance" | "agency_guidance" | "form" | "website";
        reference: string;
        url?: string;
        retrieved_at?: string;
      }[]
    ];
    last_verified: string;
    reviewer?: string;
    reviewer_notes?: string;
  };
  status: "draft" | "published" | "effective" | "archived";
  effective_from?: string;
  effective_to?: string;
  supersedes?: string[];
  superseded_by?: string;
  triggers: Condition;
  outputs: {
    /**
     * @minItems 1
     */
    permits: [
      {
        name: string;
        code?: string;
        agency: string;
      },
      ...{
        name: string;
        code?: string;
        agency: string;
      }[]
    ];
    forms?: {
      name: string;
      form_number?: string;
      url?: string;
    }[];
    submission?: {
      submission_url?: string;
      submission_email?: string;
      submission_method?: string;
    };
    agencies?: string[];
  };
  sequencing?: {
    prerequisites?: string[];
    parallel_with?: string[];
    typical_lead_time_days?: number;
    notes?: string;
  };
  explanations: {
    trigger_explanation: string;
    threshold_summary?: string;
    jurisdiction_summary?: string;
  };
  known_unknowns?: string[];
  advisories?: string[];
  tags?: string[];
  notes?: string;
};
export type Condition = LeafCondition | AllCondition | AnyCondition | NotCondition;
export type LeafCondition = {
  [k: string]: unknown;
} & {
  /**
   * Dotted snake_case path rooted at project, geometry, or derived.
   */
  field: string;
  operator: "=" | "!=" | ">" | ">=" | "<" | "<=" | "contains" | "intersects" | "exists" | "in" | "not_in";
  value?: unknown;
};

export interface AllCondition {
  /**
   * @minItems 1
   */
  all: [Condition, ...Condition[]];
}
export interface AnyCondition {
  /**
   * @minItems 1
   */
  any: [Condition, ...Condition[]];
}
export interface NotCondition {
  not: Condition;
}
